name: Gradle

on:
  push:
    branches: master
   # pull_request:
   # branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Build Only
        run: | 
          gradle wrapper --gradle-version 6.7
          gradle clean build
