name: Gradle

on:
  push:
    branches: master
   # pull_request:
   # branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.7
      - name: Build Only
        run: |
          gradle clean build
