name: Publish

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Gradle
    steps:
      - uses: actions/checkout@v2
     # - uses: gradle/gradle-build-action@v2
      #  with:
       #   gradle-version: 6.7
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '8'
      - name: Build Only
        run: |
          java -version
          gradle clean build
          echo "${{ secrets.GRADLE_SECRET == 'qwerty'}}"
          echo "${{ secrets.GRADLE_USR == 'hieu'}}"
          echo "${{ secrets.GRADLE_PSW == '1234'}}"
          
