name: Publish

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Gradle
    steps:
      - uses: actions/checkout@master
     # - uses: gradle/gradle-build-action@v2
      #  with:
       #   gradle-version: 6.7
      - name: Build Only
        run: |
          echo "${{ secrets.GRADLE_SECRET == 'qwerty'}}"
          echo "${{ secrets.GRADLE_USR == 'hieu'}}"
          echo "${{ secrets.GRADLE_PSW == '1234'}}"
          
