name: Publish

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
     # - uses: gradle/gradle-build-action@v2
      #  with:
       #   gradle-version: 6.7
      - name: Build Only
        run: |
          echo "${{ secrets.GRADLE_SECRET }}"
          echo "${{ env.GRADLE_PUBLISH_USR }}"
          echo "${{ env.GRADLE_PUBLISH_PSW }}"
          
